apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-api
  namespace: atlas-events
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-scraper
  namespace: atlas-events
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-web
  namespace: atlas-events
spec:
  replicas: 2
