apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - atlas-api/deployment.yaml
  - atlas-api/service.yaml
  - atlas-api/configmap.yaml
  - atlas-scraper/deployment.yaml
  - atlas-scraper/configmap.yaml
  - atlas-web/deployment.yaml
  - atlas-web/service.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - cronjob.yaml
